# Generated by Django 2.1.7 on 2019-03-28 12:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0004_auto_20190328_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoapi.City')),
            ],
            bases=('geoapi.city',),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geoapi.Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='capital',
            name='capital_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='geoapi.Country'),
        ),
    ]
