# Generated by Django 2.1.7 on 2019-03-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0007_auto_20190328_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='capital_of',
        ),
        migrations.RemoveField(
            model_name='capital',
            name='city_ptr',
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
