# Generated by Django 2.1.7 on 2019-03-29 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0010_auto_20190329_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
