# Generated by Django 2.1.7 on 2019-04-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0015_capital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capital',
            options={'verbose_name': 'capital', 'verbose_name_plural': 'capitals'},
        ),
    ]
