# Generated by Django 2.1.7 on 2019-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0016_auto_20190404_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photos',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
