# Generated by Django 2.1.7 on 2019-04-05 12:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import geoapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0018_auto_20190405_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='geometry')),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=geoapi.models.get_image_path, verbose_name='image'),
        ),
    ]
