# Generated by Django 2.1.7 on 2019-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
