# Generated by Django 2.1.7 on 2019-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0003_city_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
