# Generated by Django 2.1.7 on 2019-03-28 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0005_auto_20190328_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
