# Generated by Django 2.1.7 on 2019-04-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0013_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='capital_of',
        ),
        migrations.RemoveField(
            model_name='capital',
            name='city_ptr',
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
