# Generated by Django 2.1.7 on 2019-04-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0014_auto_20190404_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_of', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='geoapi.Country')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geoapi.City')),
            ],
        ),
    ]
