# Generated by Django 2.1.7 on 2019-04-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0017_city_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='photos',
        ),
        migrations.AddField(
            model_name='image',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapi.City', verbose_name='city'),
        ),
    ]
