# Generated by Django 2.1.7 on 2019-04-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0020_auto_20190408_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='capital_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geoapi.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoapi.Country', verbose_name='country'),
        ),
    ]
