# Generated by Django 2.1.7 on 2019-04-02 09:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0011_auto_20190329_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geoapi.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='desription'),
        ),
        migrations.AlterField(
            model_name='city',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
